apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-stats-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spotify-stats
  template:
    metadata:
      labels:
        app: spotify-stats
    spec:
      containers:
      - name: spotify-stats
        image: localhost:32000/spotify-stats:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: spotify-stats-service
spec:
  selector:
    app: spotify-stats
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spotify-stats-ingress
spec:
  # https://github.com/STRRL/cloudflare-tunnel-ingress-controller
  ingressClassName: cloudflare-tunnel
  rules:
  - host: spotify.cyberdeck.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spotify-stats-service
            port:
              number: 80
